# Generated by Django 5.0.4 on 2024-04-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='Collection_name',
            new_name='collection_name',
        ),
    ]
